version: '3.8'
services:
  
  forumjs:
    image: forumjs
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ForumJs
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456

    ports:
      - '3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
      
volumes:
  db:
    driver: local